name: Demigods-Panel
description: A web panel for Demigods that provides quick stat access, administrative functions, and more!
main: com.censoredsoftware.demigods.panel.DemigodsPanel
version: ${project.parent.version}
authors: [_Alex, HmmmQuestionMark]
depend: [Demigods]