## Miscellaneous Settings ##
misc:
    welcome_message: true
    tag_messages: true
    console_debug: true
    balance_teams: true

## Language Settings ##
language: 'english'

## Restrictions ##
restrictions:
    friendly_fire: false
    disabled_worlds:
        - world_the_end

## Generation ##
generation:
    min_blocks_between_altars: 450
    altar_chance: 4.8 #percent

## Regeneration ##
regeneration_rates:
    favor: 20

## Zones ##
zones:
    prayer_radius: 2
    shrine_radius: 8
    altar_radius: 16
    obelisk_radius: 16
    allow_skills_anywhere: false
    pvp_area_delay_time: 10

## Multipliers ##
multipliers:
    favor: 1.0
    skill_points: 1.0

## Caps ##
caps:
    skills: 100
    favor: 20000
    target_range: 100
    obelisks_per_character: 3

## Bonuses ##
bonuses:
    mvp_skill_points: 5

## Statistics ##
stats:
    display_freq: 0

## Character Settings ##
character:
    max_caps_in_name: 3
    defaults:
        favor: 500
        max_favor: 750

## Battle Settings ##
battles:
    min_range: 16
    merge_range: 30
    min_duration: 30
    duration_multiplier: 15
    min_kills: 3
    max_kills: 15
    blocked_commands:
        - 'spawn'
        - 'home'
        - 'sethome'
        - 'call'
        - 'bring'
        - 'myhome'
        - 'back'

## Administrative Settings ##
admin:
    wand_tool: 369

## Data ##
saving:
    freq: 300
