name: Demigods
main: com.censoredsoftware.demigods.DemigodsPlugin
version: ${project.version}
authors: [_Alex, HmmmQuestionMark]
softdepend: [WorldEdit, WorldGuard, Multiverse-Core]
commands:
    demigods:
        usage: /demigods [category] [subcategory]
        aliases: [demigod, dg]
        permission: demigods.basic
    deity:
        usage: /deity
        permission: demigods.basic
    check:
        usage: /check
        aliases: [c]
        permission: demigods.basic
    owner:
        usage: /owner <character>
        aliases: [o]
        permission: demigods.basic
    leaderboard:
        usage: /leaderboard
        aliases: [l]
        permission: demigods.basic
    alliance:
        usage: /alliance
        aliases: [a]
        permission: demigods.basic
    names:
        usage: /names
        aliases: [n]
        permission: demigods.basic
    test1:
        usage: /test1
        permission: demigods.admin
    test2:
        usage: /test2
        permission: demigods.admin
    test3:
        usage: /test3
        permission: demigods.admin
    obelisk:
        usage: /obelisk <add|remove> <player|character> <name>
    hspawn:
        usage: /hspawn
    nearestaltar:
        usage: /nearestaltar
    binds:
        usage: /binds
        permission: demigods.basic
    values:
        usage: /values
        aliases: [v]
        permission: demigods.basic
permissions:
    demigods.basic:
        description: The default permission for players.
        default: true
    demigods.basic.create:
        description: Allows the player to create a character.
        default: true
    demigods.basic.forsake:
        description: Allows the player to forsake their Deity.
        default: true
    demigods.admin:
        description: The default permission for admins.
        default: op
    demigods.bypass.pvpareacooldown:
        description: Bypass the wait for leaving/entering PVP zones.
        default: false
    demigods.god.zeus:
        description: Allows the player to use Zeus.
        default: true
    demigods.god.poseidon:
        description: Allows the player to use Poseidon.
        default: true
    demigods.god.hades:
        description: Allows the player to use Hades.
        default: true
    demigods.titan.oceanus:
        description: Allows the player to use Oceanus.
        default: true
    demigods.titan.prometheus:
        description: Allows the player to use Prometheus.
        default: true
    demigods.titan.iapetus:
        description: Allows the player to use Iapetus.
        default: true
    demigods.fate.clotho:
        description: Allows the player to use Clotho.
        default: false
    demigods.fate.lachesis:
        description: Allows the player to use Lachesis.
        default: false
    demigods.fate.atropos:
        description: Allows the player to use Atropos.
        default: false