name: Demigods
main: com.censoredsoftware.demigods.DemigodsPlugin
version: ${project.version}
authors: [_Alex, HmmmQuestionMark]
softdepend: [WorldEdit, WorldGuard]
commands:
    demigods:
        usage: /demigods [category] [subcategory]
        aliases: [demigod, dg]
        permission: demigods.basic
    deity:
        usage: /deity
        permission: demigods.basic
    check:
        usage: /check
        permission: demigods.basic
    owner:
        usage: /owner <character>
        permission: demigods.basic
    removechar:
        usage: /removechar <name>
        permission: demigods.basic
    test1:
        usage: /test1
        permission: demigods.admin
    test2:
        usage: /test2
        permission: demigods.admin
    test3:
        usage: /test3
        permission: demigods.admin
    hspawn:
        usage: /hspawn
    makecharacters:
        usage: /makecharacters <howmany>
    binds:
        usage: /binds
        permission: demigods.basic
permissions:
    demigods.basic:
        description: The default permission for players.
        default: true
    demigods.admin:
        description: The default permission for admins.
        default: op
    demigods.bypass.pvpareacooldown:
        description: Bypass the wait for leaving/entering PVP zones.
        default: false
    demigods.god:
        default: true
    demigods.titan:
        default: true
    demigods.insignian:
        default: false
    demigods.god.zeus:
        description: Allows the player to use Zeus.
        default: true
    demigods.god.poseidon:
        description: Allows the player to use Poseidon.
        default: true
    demigods.titan.oceanus:
        description: Allows the player to use Oceanus.
        default: true
    demigods.titan.prometheus:
        description: Allows the player to use Prometheus.
        default: true
    demigods.insignian.disco:
        description: Disco.
        default: false
    demigods.tutorial:
        description: Allows the player to participate in the Tutorial quest.
        default: true
    demigods.shrine:
        default: true
    demigods.altar:
        default: true
    demigods.update:
        default: op