## Global Settings ##
auto_update: false
data_debug: false
broadcast_new_deities: true
friendly_fire: false
allow_skills_anywhere: false
balance_teams: true
pvp_area_delay_time: 10
inactive_worlds:
#- world_nodemigods

## Statistic Caps, Multipliers, and Related ##
global_favor_multiplier: 1.0
global_exp_multiplier: 1.0
global_max_favor: 20000
max_target_range: 100
pvp_exp_bonus: 1.5
stat_display_frequency_in_seconds: 0
start_delay_seconds: 60.0
favor_regen_seconds: 10.0
save_interval_seconds: 300
ascension_cap: 100

## Character Creation Settings ##
default_favor: 500
default_max_favor: 750
default_devotion: 200
default_ascensions: 1

## Administrative Settings ##
admin_wand_tool: 268

## Database Settings ##
database:
    mysql:
        use: true
        db_name: minecraft
        username: root
        password: ''
        host: localhost
        port: 3306
    sqlite:
        use: false