name: Demigods
main: com.legit2.Demigods.Demigods
version: 3.0.@BUILD@
authors: [_Alex, HmmmQuestionMark]
softdepend: [SQLibrary, TagAPI, WorldEdit, WorldGuard]
commands:
    dg:
        usage: /dg [category] [subcategory]
        permission: demigods.basic
    viewmaps:
        usage: /viewmaps
        permission: demigods.basic
    check:
        usage: /check
        permission: demigods.basic
    createchar:
        usage: /createchar <name> <deity>
        permission: demigods.basic
    switchchar:
        usage: /switchchar <name>
        permission: demigods.basic
    removechar:
        usage: /removechar <name>
        permission: demigods.basic
    test1:
        usage: /test1
        permission: demigods.basic
permissions:
    demigods.basic:
        description: The default permission for players.
        default: true
    demigods.admin:
        description: The default permission for admins.
        default: op
    demigods.bypass.pvpareacooldown:
        description: Bypass the wait for leaving/entering PVP zones.
        default: false