name: Demigods-Greek
description: The Greek addon for Demigods RPG.
main: com.demigodsrpg.demigods.greek.GreekMythos
version: ${project.parent.version}
authors: [_Alex, HmmmQuestionMark]
depend: [Demigods]