name: Demigods-Exclusive
description: The exclusive addon for official Demigods RPG server.
main: com.demigodsrpg.demigods.exclusive.ExclusiveMythos
version: ${project.parent.version}
authors: [_Alex, HmmmQuestionMark]
depend: [Demigods]
commands:
  world:
    usage: /<command> [subcommand] [args] ...
permissions:
  exclusive.world:
    default: op