## Global Settings ##
auto_update: false
broadcast_new_deities: true
friendly_fire: false
allow_skills_anywhere: false
balance_teams: true
pvp_area_delay_seconds: 2.0
inactive_worlds:
#- world_nodemigods

## Statistic Caps, Multipliers, and Related ##
globalfavormultiplier: 1.0
globalexpmultiplier: 1.0
globalfavorcap: 20000
max_target_range: 100
pvp_exp_bonus: 1.5
stat_display_frequency_in_seconds: 0
start_delay_seconds: 60.0
favor_regen_seconds: 0.5
max_favor: 10000
save_interval_seconds: 300
ascension_cap: 100

## Database Settings ##
database:
    mysql:
        use: true
        db_name: minecraft
        username: root
        password:
        host: localhost
        port: '3306'