name: Demigods
main: com.legit2.Demigods.Demigods
version: 3.0.0
softdepend: [SQLibrary, WorldEdit, WorldGuard, Factions]
permissions:
    demigods.basic:
        description: The default permission for players.
        default: true