name: Demigods
main: com.legit2.Demigods.Demigods
version: 3.0.0
depend: [SQLibrary]
permissions:
    demigods.basic:
        description: The default permission for players.
        default: true