name: Demigods
main: com.legit2.Demigods.Demigods
version: 3.0.0
softdepend: [SQLibrary, TagAPI, WorldEdit, WorldGuard]
commands:
    dg:
        usage: /dg [category] [subcategory]
        permission: demigods.basic
    viewmaps:
        usage: /viewmaps
        permission: demigods.basic
    check:
        usage: /check
        permission: demigods.basic
    claim:
        usage: /claim <deity>
        permission: demigods.basic
    setalliance:
        usage: /setalliance <player> <alliance>
        permission: demigods.admin
    setfavor:
        usage: /setfavor <player> <favor>
        permission: demigods.admin
    setascensions:
        usage: /setascensions <player> <ascensions>
        permission: demigods.admin
    setdevotion:
        usage: /setdevotion <player> <deity> <devotion>
        permission: demigods.admin
    givedeity:
        usage: /givedeity <player> <deity>
        permission: demigods.admin
    removeplayer:
        usage: /removeplayer <player>
        permission: demigods.admin
    createchar:
        usage: /createchar <name> <deity>
        permission: demigods.basic
    test1:
        usage: /test1
        permission: demigods.basic
permissions:
    demigods.basic:
        description: The default permission for players.
        default: true
    demigods.admin:
        description: The default permission for admins.
        default: op
    demigods.bypass.pvpareacooldown:
        description: Bypass the wait for leaving/entering PVP zones.
        default: false