name: Demigods
description: The official Demigods RPG experience for survival/PvP Minecraft servers.
main: com.demigodsrpg.demigods.engine.DemigodsPlugin
load: POSTWORLD
version: ${project.parent.version}
authors: [_Alex, HmmmQuestionMark]
softdepend: [CensoredLib, CensoredLib-Web, WorldEdit, WorldGuard]
commands:
# Main Command
    demigods:
        usage: /demigods [category] [subcategory]
        aliases: [demigod, dg]
        permission: demigods.basic
    deity:
        usage: /deity
        aliases: [d]
        permission: demigods.basic
# General Commands
    check:
        usage: /check
        aliases: [c]
        permission: demigods.basic
    owner:
        usage: /owner <character>
        aliases: [o]
        permission: demigods.basic
    leaderboard:
        usage: /leaderboard
        aliases: [l]
        permission: demigods.basic
    alliance:
        usage: /alliance
        aliases: [a]
        permission: demigods.basic
    names:
        usage: /names
        aliases: [n]
        permission: demigods.basic
    tributes:
        usage: /tributes
        aliases: [t, v, values]
        permission: demigods.basic
    binds:
        usage: /binds
        aliases: [b]
        permission: demigods.basic
    skills:
        usage: /skills
        aliases: [s]
        permission: demigods.basic
# Development Commands
    obelisk:
        usage: /obelisk [add|remove] [player|character] [name]
    test1:
        usage: /test1
        permission: demigods.admin
    test2:
        usage: /test2
        #permission: demigods.admin
    test3:
        usage: /test3
        #permission: demigods.admin
